package com.mycompany.assignment1;

public class AddMilestonetoPlanPage extends javax.swing.JFrame {
    private User currentUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddMilestonetoPlanPage.class.getName());
    public AddMilestonetoPlanPage(User currentUser) {
    this.currentUser = currentUser;
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddM_Label = new javax.swing.JLabel();
        PlanID_Field = new javax.swing.JTextField();
        PlanID_Label = new javax.swing.JLabel();
        PID_Ex_Label = new javax.swing.JLabel();
        Milestone_Label = new javax.swing.JLabel();
        Milestone_Field = new javax.swing.JTextField();
        Back_Button = new javax.swing.JButton();
        Add_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddM_Label.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        AddM_Label.setText("Add Milestone");

        PlanID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanID_FieldActionPerformed(evt);
            }
        });

        PlanID_Label.setText("Enter Plan ID to add milestone");

        PID_Ex_Label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PID_Ex_Label.setForeground(new java.awt.Color(102, 102, 102));
        PID_Ex_Label.setText("Ex: P-Studentcode-Coursecode-####");

        Milestone_Label.setText("Milestone");

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        Add_Button.setText("Add");
        Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Add_Button)
                .addGap(32, 32, 32)
                .addComponent(Back_Button)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(AddM_Label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Milestone_Label)
                            .addComponent(PlanID_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PID_Ex_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PlanID_Field))
                            .addComponent(Milestone_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(AddM_Label)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlanID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlanID_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PID_Ex_Label)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Milestone_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Milestone_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Add_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(Back_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlanID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlanID_FieldActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
        new OfficerPage(currentUser).setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ButtonActionPerformed
    String planId = PlanID_Field.getText().trim();
    String newMilestone = Milestone_Field.getText().trim();
    if (planId.isEmpty() || newMilestone.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Fields cannot be empty.");
        return;
    }
    java.util.List<String> lines = new java.util.ArrayList<>();
    boolean found = false;
    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("recovery_plans.csv"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");
            if (data[0].equals(planId)) {
                found = true;
                if (data.length < 10) {
                    String[] expanded = new String[10];
                    System.arraycopy(data, 0, expanded, 0, data.length);
                    for (int i = data.length; i < 10; i++) expanded[i] = "";
                    data = expanded;
                }
                if (data[9].isEmpty()) {
                    data[9] = newMilestone;
                } else {
                    data[9] = data[9] + " | " + newMilestone;
                }
                line = String.join(",", data);
            }
            lines.add(line);
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error reading file.");
        return;
    }
    if (!found) {
        javax.swing.JOptionPane.showMessageDialog(this, "Plan ID not found.");
        return;
    }
    try (java.io.FileWriter fw = new java.io.FileWriter("recovery_plans.csv")) {
        for (String l : lines) fw.write(l + "\n");
        javax.swing.JOptionPane.showMessageDialog(this, "Milestone added.");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error saving file.");
    }
    }//GEN-LAST:event_Add_ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddM_Label;
    private javax.swing.JButton Add_Button;
    private javax.swing.JButton Back_Button;
    private javax.swing.JTextField Milestone_Field;
    private javax.swing.JLabel Milestone_Label;
    private javax.swing.JLabel PID_Ex_Label;
    private javax.swing.JTextField PlanID_Field;
    private javax.swing.JLabel PlanID_Label;
    // End of variables declaration//GEN-END:variables
}
