package com.mycompany.assignment1;

import javax.swing.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;


public class AddUserPage extends javax.swing.JFrame {
    private User currentUser;
    private final String filePath = System.getProperty("user.dir") + "/users.csv";


public AddUserPage(User currentUser) {
    this.currentUser = currentUser;
    initComponents();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExLabel = new javax.swing.JLabel();
        AddU_Label = new javax.swing.JLabel();
        Pass_Field = new javax.swing.JPasswordField();
        UserID_Field = new javax.swing.JTextField();
        Username_Field = new javax.swing.JTextField();
        Email_Field = new javax.swing.JTextField();
        UserID_Label = new javax.swing.JLabel();
        Role_CB = new javax.swing.JComboBox<>();
        User_Label = new javax.swing.JLabel();
        User_Label1 = new javax.swing.JLabel();
        Add_Button = new javax.swing.JButton();
        Email_Label = new javax.swing.JLabel();
        UID_Ex_Label = new javax.swing.JLabel();
        Role_Label = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();

        ExLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ExLabel.setForeground(new java.awt.Color(102, 102, 102));
        ExLabel.setText("Ex: APU##");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddU_Label.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        AddU_Label.setText("Add User ");

        UserID_Label.setText("UserID");

        Role_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "AcademicOfficer" }));

        User_Label.setText("Password");

        User_Label1.setText("Username");

        Add_Button.setText("Add");
        Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ButtonActionPerformed(evt);
            }
        });

        Email_Label.setText("Email");

        UID_Ex_Label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        UID_Ex_Label.setForeground(new java.awt.Color(102, 102, 102));
        UID_Ex_Label.setText("Ex: APU##");

        Role_Label.setText("Role");

        Back_Button.setText("Back");
        Back_Button.setToolTipText("");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserID_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(User_Label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(User_Label1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UID_Ex_Label)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pass_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(Role_Label)
                                        .addGap(6, 6, 6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(UserID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(Email_Label)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Role_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(AddU_Label)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(AddU_Label)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserID_Label)
                    .addComponent(UserID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UID_Ex_Label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User_Label1)
                    .addComponent(Role_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Role_Label))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pass_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User_Label)
                    .addComponent(Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ButtonActionPerformed
        String id = UserID_Field.getText().trim();
        String username = Username_Field.getText().trim();
        String email = Email_Field.getText().trim();
        String password = new String(Pass_Field.getPassword()).trim();
        String role = Role_CB.getSelectedItem().toString();

        if (id.isEmpty() || username.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled.");
            return;
        }
        String csvLine = id + "," + username + "," + email + "," + password + "," + role + ",,";

        try (BufferedWriter bw = new BufferedWriter(new FileWriter("users.csv", true))) {
            bw.write(csvLine);
            bw.newLine();
            JOptionPane.showMessageDialog(this, "User added successfully.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error writing to file: " + e.getMessage());
        }
    }//GEN-LAST:event_Add_ButtonActionPerformed

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
        new AdminPage(currentUser).setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddU_Label;
    private javax.swing.JButton Add_Button;
    private javax.swing.JButton Back_Button;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JLabel ExLabel;
    private javax.swing.JPasswordField Pass_Field;
    private javax.swing.JComboBox<String> Role_CB;
    private javax.swing.JLabel Role_Label;
    private javax.swing.JLabel UID_Ex_Label;
    private javax.swing.JTextField UserID_Field;
    private javax.swing.JLabel UserID_Label;
    private javax.swing.JLabel User_Label;
    private javax.swing.JLabel User_Label1;
    private javax.swing.JTextField Username_Field;
    // End of variables declaration//GEN-END:variables
}
