package com.mycompany.assignment1;

import java.io.FileWriter;

public class CreateRecoveryPlanPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateRecoveryPlanPage.class.getName());
    private User currentUser;
    public CreateRecoveryPlanPage(User currentUser) {
    this.currentUser = currentUser;
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CRP_Label = new javax.swing.JLabel();
        StudentID_Field = new javax.swing.JTextField();
        PlanID_Field = new javax.swing.JTextField();
        Back_Button1 = new javax.swing.JButton();
        StudentN_Field = new javax.swing.JTextField();
        ExamG_Field = new javax.swing.JTextField();
        CourseID_Field = new javax.swing.JTextField();
        AssG_Field = new javax.swing.JTextField();
        GPA_Field = new javax.swing.JTextField();
        Status_Field = new javax.swing.JTextField();
        PlanID_Label = new javax.swing.JLabel();
        PID_Ex_Label = new javax.swing.JLabel();
        StudentID_Label = new javax.swing.JLabel();
        StudentN_Label = new javax.swing.JLabel();
        CourseID_Label = new javax.swing.JLabel();
        SID_Ex_Label = new javax.swing.JLabel();
        CourseN_Field = new javax.swing.JTextField();
        CID_Ex_Label = new javax.swing.JLabel();
        CourseID_Label1 = new javax.swing.JLabel();
        ExamG_Label = new javax.swing.JLabel();
        AssG_Label = new javax.swing.JLabel();
        GPA_Label = new javax.swing.JLabel();
        Status_Label = new javax.swing.JLabel();
        Save_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CRP_Label.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        CRP_Label.setText("Create Recovery Plan");

        PlanID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanID_FieldActionPerformed(evt);
            }
        });

        Back_Button1.setText("Back");
        Back_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_Button1ActionPerformed(evt);
            }
        });

        ExamG_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamG_FieldActionPerformed(evt);
            }
        });

        AssG_Field.setToolTipText("");

        PlanID_Label.setText("Plan ID");

        PID_Ex_Label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PID_Ex_Label.setForeground(new java.awt.Color(102, 102, 102));
        PID_Ex_Label.setText("Ex: P-Studentcode-Coursecode-####");

        StudentID_Label.setText("Student ID");

        StudentN_Label.setText("Student Name");

        CourseID_Label.setText("Course ID");

        SID_Ex_Label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        SID_Ex_Label.setForeground(new java.awt.Color(102, 102, 102));
        SID_Ex_Label.setText("Ex: S####");

        CID_Ex_Label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        CID_Ex_Label.setForeground(new java.awt.Color(102, 102, 102));
        CID_Ex_Label.setText("Ex: C####");

        CourseID_Label1.setText("Course Name");

        ExamG_Label.setText("Exam Grade");

        AssG_Label.setText("Assignment Grade");

        GPA_Label.setText("GPA");

        Status_Label.setText("Status");

        Save_Button.setText("Save");
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PlanID_Label)
                    .addComponent(StudentID_Label)
                    .addComponent(StudentN_Label)
                    .addComponent(CourseID_Label)
                    .addComponent(CourseID_Label1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(CRP_Label)
                        .addGap(155, 155, 155))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CID_Ex_Label)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PID_Ex_Label)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SID_Ex_Label)
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(GPA_Label))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PlanID_Field)
                                            .addComponent(CourseID_Field)
                                            .addComponent(StudentN_Field)
                                            .addComponent(StudentID_Field, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(CourseN_Field))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(ExamG_Label)
                                                    .addComponent(AssG_Label)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(Status_Label)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ExamG_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AssG_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GPA_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Status_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(107, 107, 107))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Save_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(Back_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(CRP_Label)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlanID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExamG_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlanID_Label)
                    .addComponent(ExamG_Label))
                .addGap(3, 3, 3)
                .addComponent(PID_Ex_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssG_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentID_Label)
                    .addComponent(AssG_Label))
                .addGap(7, 7, 7)
                .addComponent(SID_Ex_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentN_Label)
                    .addComponent(GPA_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GPA_Label))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseID_Label)
                    .addComponent(Status_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Status_Label))
                .addGap(1, 1, 1)
                .addComponent(CID_Ex_Label)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CourseN_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CourseID_Label1))
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Save_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Back_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_Button1ActionPerformed
        this.dispose();
        new OfficerPage(currentUser).setVisible(true);
    }//GEN-LAST:event_Back_Button1ActionPerformed

    private void PlanID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlanID_FieldActionPerformed

    private void ExamG_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamG_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExamG_FieldActionPerformed

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
    String planId = PlanID_Field.getText();
    String studentId = StudentID_Field.getText();
    String studentName = StudentN_Field.getText();
    String courseId = CourseID_Field.getText();
    String courseName = CourseN_Field.getText();
    double examGrade = Double.parseDouble(ExamG_Field.getText());
    double assignmentGrade = Double.parseDouble(AssG_Field.getText());
    double gpa = Double.parseDouble(GPA_Field.getText());
    String status = Status_Field.getText();
    String csvLine = String.join(",",
        planId,
        studentId,
        studentName,
        courseId,
        courseName,
        String.valueOf(examGrade),
        String.valueOf(assignmentGrade),
        String.valueOf(gpa),
        status
    );
    try (FileWriter fw = new FileWriter("recovery_plans.csv", true)) {
        fw.write(csvLine + "\n");
        javax.swing.JOptionPane.showMessageDialog(this, "Recovery plan saved successfully.");
    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error saving recovery planPlanID_Field.");
    }
  }//GEN-LAST:event_Save_ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AssG_Field;
    private javax.swing.JLabel AssG_Label;
    private javax.swing.JButton Back_Button1;
    private javax.swing.JLabel CID_Ex_Label;
    private javax.swing.JLabel CRP_Label;
    private javax.swing.JTextField CourseID_Field;
    private javax.swing.JLabel CourseID_Label;
    private javax.swing.JLabel CourseID_Label1;
    private javax.swing.JTextField CourseN_Field;
    private javax.swing.JTextField ExamG_Field;
    private javax.swing.JLabel ExamG_Label;
    private javax.swing.JTextField GPA_Field;
    private javax.swing.JLabel GPA_Label;
    private javax.swing.JLabel PID_Ex_Label;
    private javax.swing.JTextField PlanID_Field;
    private javax.swing.JLabel PlanID_Label;
    private javax.swing.JLabel SID_Ex_Label;
    private javax.swing.JButton Save_Button;
    private javax.swing.JTextField Status_Field;
    private javax.swing.JLabel Status_Label;
    private javax.swing.JTextField StudentID_Field;
    private javax.swing.JLabel StudentID_Label;
    private javax.swing.JTextField StudentN_Field;
    private javax.swing.JLabel StudentN_Label;
    // End of variables declaration//GEN-END:variables
}
