package com.mycompany.assignment1;

import javax.swing.JOptionPane;

public class DeletePlanPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeletePlanPage.class.getName());
    private User currentUser;
    public DeletePlanPage(User currentUser) {
    this.currentUser = currentUser;
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back_Button = new javax.swing.JButton();
        UpdatePS_Label = new javax.swing.JLabel();
        Delete_Button = new javax.swing.JButton();
        PlanID_Field = new javax.swing.JTextField();
        PlanID_Label = new javax.swing.JLabel();
        PID_Ex_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        UpdatePS_Label.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        UpdatePS_Label.setText("Delete Plan ");

        Delete_Button.setText("Delete");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });

        PlanID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanID_FieldActionPerformed(evt);
            }
        });

        PlanID_Label.setText("Enter Plan ID to delete");

        PID_Ex_Label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PID_Ex_Label.setForeground(new java.awt.Color(102, 102, 102));
        PID_Ex_Label.setText("Ex: P-Studentcode-Coursecode-####");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_Button)
                .addGap(32, 32, 32)
                .addComponent(Back_Button)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(UpdatePS_Label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(PlanID_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PID_Ex_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PlanID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(UpdatePS_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlanID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlanID_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PID_Ex_Label)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Delete_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
        new OfficerPage(currentUser).setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
      String planId = PlanID_Field.getText().trim();
        if (planId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Plan ID cannot be empty.");
            return;
        }
        java.util.List<String> lines = new java.util.ArrayList<>();
        boolean found = false;
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("recovery_plans.csv"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data[0].equals(planId)) {
                    found = true;
                    continue;
                }
                lines.add(line);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error reading file.");
            return;
        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Plan ID not found.");
            return;
        }
        try (java.io.FileWriter fw = new java.io.FileWriter("recovery_plans.csv")) {
            for (String l : lines) fw.write(l + "\n");
            JOptionPane.showMessageDialog(this, "Plan deleted.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving file.");
        }
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void PlanID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlanID_FieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JLabel PID_Ex_Label;
    private javax.swing.JTextField PlanID_Field;
    private javax.swing.JLabel PlanID_Label;
    private javax.swing.JLabel UpdatePS_Label;
    // End of variables declaration//GEN-END:variables
}
