package com.mycompany.assignment1;

import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GenerateReportPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GenerateReportPage.class.getName());
    private User currentUser;
    public GenerateReportPage(User currentUser) {
    this.currentUser = currentUser;
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenerateAR_Label = new javax.swing.JLabel();
        Back_Button = new javax.swing.JButton();
        Generate_Button = new javax.swing.JButton();
        StudentID_Label = new javax.swing.JLabel();
        StudentID_Field = new javax.swing.JTextField();
        Semester_CB = new javax.swing.JComboBox<>();
        Semester_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GenerateAR_Label.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        GenerateAR_Label.setText("Generate Academic Report");

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        Generate_Button.setText("Generate");
        Generate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generate_ButtonActionPerformed(evt);
            }
        });

        StudentID_Label.setText("Enter student ID to generate their report");

        Semester_CB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Summer", "Spring", "Fall" }));

        Semester_Label.setText("Pick semester");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Generate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addComponent(Back_Button)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GenerateAR_Label)
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(StudentID_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Semester_Label)
                        .addGap(42, 42, 42)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Semester_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(GenerateAR_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentID_Label)
                    .addComponent(StudentID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Semester_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Semester_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Generate_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
        new OfficerPage(currentUser).setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Generate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generate_ButtonActionPerformed
    String studentId = StudentID_Field.getText().trim();
    String semester = Semester_CB.getSelectedItem().toString();
    if (studentId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Student ID cannot be empty.");
        return;
    }
    Student student = loadStudentFromCSV(studentId);
    if (student == null) {
        JOptionPane.showMessageDialog(this, "Student with ID '" + studentId + "' not found.");
        return;
    }
    Map<String, Course> courseMap = loadCoursesFromCSV();
    List<EnrolledCourse> enrollments = loadEnrollmentsFromCSV(studentId, courseMap);
    for (EnrolledCourse ec : enrollments) {
        student.addEnrolledCourse(ec);
    }
    boolean success = new AcademicReportGenerator().generateReport(student, semester);
    if (success) {
        JOptionPane.showMessageDialog(this, "PDF generated successfully.");
    } else {
        JOptionPane.showMessageDialog(this, "Failed to generate PDF.");
    }
    }//GEN-LAST:event_Generate_ButtonActionPerformed

    private Student loadStudentFromCSV(String studentId) {
    String file = "student_information.csv";
    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line = br.readLine(); 
        while ((line = br.readLine()) != null) {
            if (line.trim().isEmpty()) continue;
            String[] p = line.split(",", -1);
            if (p.length < 6) continue;
            String id = p[0].trim();
            if (id.equalsIgnoreCase(studentId.trim())) {
                String firstName = p[1].trim();
                String lastName = p[2].trim();
                String major = p[3].trim();
                String year = p[4].trim();
                String email = p[5].trim();
                return new Student(id, firstName, lastName, major, year, email);
            }
        }
    } catch (Exception e) {
        System.out.println("Error loading student: " + e.getMessage());
    }   
    return null;
}

private Map<String, Course> loadCoursesFromCSV() {
    Map<String, Course> map = new HashMap<>();
    String file = "course_assessment_information.csv";
    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line = br.readLine(); 
        while ((line = br.readLine()) != null) {
            if (line.trim().isEmpty()) continue;
            String[] p = line.split(",", -1);
            if (p.length < 7) continue;
            String courseId = p[0].trim();
            String courseName = p[1].trim();
            int credits = Integer.parseInt(p[2].trim());
            String semester = p[3].trim();
            String instructor = p[4].trim();
            double examWeight = Double.parseDouble(p[5].trim());
            double assignmentWeight = Double.parseDouble(p[6].trim());
            Course c = new Course(courseId, courseName, credits, semester, instructor, examWeight, assignmentWeight);
            map.put(courseId, c);
        }
    } catch (Exception e) {
        System.out.println("Error loading courses: " + e.getMessage());
    }
    return map;
}

private List<EnrolledCourse> loadEnrollmentsFromCSV(String studentId, Map<String, Course> courseMap) {
    List<EnrolledCourse> list = new ArrayList<>();
    String file = "enrollments.csv";
    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line = br.readLine(); 
        while ((line = br.readLine()) != null) {
            if (line.trim().isEmpty()) continue;
            String[] p = line.split(",", -1);
            if (p.length < 5) continue;
            String sid = p[0].trim();
            if (!sid.equalsIgnoreCase(studentId.trim())) {
                continue;
            }
            String courseId = p[1].trim();
            double examGrade = Double.parseDouble(p[2].trim());
            double assignmentGrade = Double.parseDouble(p[3].trim());
            Course c = courseMap.get(courseId);
            if (c == null) {
                continue;
            }
            EnrolledCourse ec = new EnrolledCourse(null, c, assignmentGrade, examGrade);
            list.add(ec);
        }
    } catch (Exception e) {
        System.out.println("Error loading enrollments: " + e.getMessage());
    }
    return list;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel GenerateAR_Label;
    private javax.swing.JButton Generate_Button;
    private javax.swing.JComboBox<String> Semester_CB;
    private javax.swing.JLabel Semester_Label;
    private javax.swing.JTextField StudentID_Field;
    private javax.swing.JLabel StudentID_Label;
    // End of variables declaration//GEN-END:variables
}
