package com.mycompany.assignment1;

public class OfficerPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OfficerPage.class.getName());
    
    private User currentUser;
    
    public OfficerPage(User currentUser) {
    this.currentUser = currentUser;
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OfficerLabel = new javax.swing.JLabel();
        CheckS_Button = new javax.swing.JButton();
        CreateRP_Button = new javax.swing.JButton();
        ViewRP_Button = new javax.swing.JButton();
        AddM_Button = new javax.swing.JButton();
        EditM_Button = new javax.swing.JButton();
        UpdatePS_Button = new javax.swing.JButton();
        DeleteP_Button = new javax.swing.JButton();
        GenerateAR_Button = new javax.swing.JButton();
        Logout_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OfficerLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        OfficerLabel.setText("Officer Dashboard");

        CheckS_Button.setText("Check Student Eligibility");
        CheckS_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckS_ButtonActionPerformed(evt);
            }
        });

        CreateRP_Button.setText("Create Recovery Plan");
        CreateRP_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRP_ButtonActionPerformed(evt);
            }
        });

        ViewRP_Button.setText("View Recovery Plan");
        ViewRP_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRP_ButtonActionPerformed(evt);
            }
        });

        AddM_Button.setText("Add Milestone to Plan");
        AddM_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddM_ButtonActionPerformed(evt);
            }
        });

        EditM_Button.setText("Edit Milestone");
        EditM_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditM_ButtonActionPerformed(evt);
            }
        });

        UpdatePS_Button.setText("Update Plan Status");
        UpdatePS_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePS_ButtonActionPerformed(evt);
            }
        });

        DeleteP_Button.setText("Delete Plan");
        DeleteP_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteP_ButtonActionPerformed(evt);
            }
        });

        GenerateAR_Button.setText("Generate Academic Report");
        GenerateAR_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateAR_ButtonActionPerformed(evt);
            }
        });

        Logout_Button.setText("Logout");
        Logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateRP_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ViewRP_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CheckS_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdatePS_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(EditM_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OfficerLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DeleteP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AddM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(GenerateAR_Button))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)))
                .addComponent(Logout_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(OfficerLabel)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CheckS_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(EditM_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdatePS_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(CreateRP_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewRP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteP_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddM_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenerateAR_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_ButtonActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Logout_ButtonActionPerformed

    private void EditM_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditM_ButtonActionPerformed
    new EditMilestonePage(currentUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_EditM_ButtonActionPerformed

    private void GenerateAR_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateAR_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerateAR_ButtonActionPerformed

    private void DeleteP_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteP_ButtonActionPerformed
    new DeletePlanPage(currentUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_DeleteP_ButtonActionPerformed

    private void CheckS_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckS_ButtonActionPerformed
    new CheckStudentEligibilityPage(currentUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_CheckS_ButtonActionPerformed

    private void CreateRP_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRP_ButtonActionPerformed
    new CreateRecoveryPlanPage(currentUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_CreateRP_ButtonActionPerformed

    private void ViewRP_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRP_ButtonActionPerformed
    new ViewRecoveryPlanPage(currentUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ViewRP_ButtonActionPerformed

    private void AddM_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddM_ButtonActionPerformed
    new AddMilestonetoPlanPage(currentUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_AddM_ButtonActionPerformed

    private void UpdatePS_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePS_ButtonActionPerformed
    new UpdatePlanStatusPage(currentUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_UpdatePS_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddM_Button;
    private javax.swing.JButton CheckS_Button;
    private javax.swing.JButton CreateRP_Button;
    private javax.swing.JButton DeleteP_Button;
    private javax.swing.JButton EditM_Button;
    private javax.swing.JButton GenerateAR_Button;
    private javax.swing.JButton Logout_Button;
    private javax.swing.JLabel OfficerLabel;
    private javax.swing.JButton UpdatePS_Button;
    private javax.swing.JButton ViewRP_Button;
    // End of variables declaration//GEN-END:variables
}
