package com.mycompany.assignment1;

import javax.swing.JOptionPane;

public class ResetPasswordPage extends javax.swing.JFrame {
    private User currentUser;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ResetPasswordPage.class.getName());
    public ResetPasswordPage() {
    this.currentUser = currentUser;
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back_Button = new javax.swing.JButton();
        ResetPass_Label = new javax.swing.JLabel();
        Save_Button = new javax.swing.JButton();
        UserID_Field = new javax.swing.JTextField();
        UserID_Label = new javax.swing.JLabel();
        PID_Ex_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back_Button.setText("Back");
        Back_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_ButtonActionPerformed(evt);
            }
        });

        ResetPass_Label.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        ResetPass_Label.setText("Reset Password");

        Save_Button.setText("Save");
        Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_ButtonActionPerformed(evt);
            }
        });

        UserID_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserID_FieldActionPerformed(evt);
            }
        });

        UserID_Label.setText("Enter UserID");

        PID_Ex_Label.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PID_Ex_Label.setForeground(new java.awt.Color(102, 102, 102));
        PID_Ex_Label.setText("Ex: APU#");

        Password_Label.setText("Enter new password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResetPass_Label)
                    .addComponent(Save_Button))
                .addGap(32, 32, 32)
                .addComponent(Back_Button)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserID_Label)
                    .addComponent(Password_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PID_Ex_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserID_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(Password_Field))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ResetPass_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserID_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserID_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PID_Ex_Label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_Label)
                    .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Save_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_ButtonActionPerformed
        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_Back_ButtonActionPerformed

    private void Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_ButtonActionPerformed
    String userId = UserID_Field.getText().trim();
    String newStatus = Password_Field.getText().trim();
    if (userId.isEmpty() || newStatus.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fields cannot be empty.");
        return;
    }
    java.util.List<String> lines = new java.util.ArrayList<>();
    boolean found = false;
    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("users.csv"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");
            if (data[0].equals(userId)) {
                found = true;
                if (data.length < 4) {
                    String[] expanded = new String[3];
                    System.arraycopy(data, 0, expanded, 0, data.length);
                    for (int i = data.length; i < 4; i++) expanded[i] = "";
                    data = expanded;
                }
                data[3] = newStatus;
                line = String.join(",", data);
            }
            lines.add(line);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error reading file.");
        return;
    }
    if (!found) {
        JOptionPane.showMessageDialog(this, "User ID not found.");
        return;
    }
    try (java.io.FileWriter fw = new java.io.FileWriter("users.csv")) {
        for (String l : lines) fw.write(l + "\n");
        JOptionPane.showMessageDialog(this, "Status updated.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saving file.");
    }
    }//GEN-LAST:event_Save_ButtonActionPerformed

    private void UserID_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserID_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserID_FieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Button;
    private javax.swing.JLabel PID_Ex_Label;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JLabel ResetPass_Label;
    private javax.swing.JButton Save_Button;
    private javax.swing.JTextField UserID_Field;
    private javax.swing.JLabel UserID_Label;
    // End of variables declaration//GEN-END:variables
}
